version: '3.8'

networks:
  skynet:

services:

  server:
    build:
      context: .
    networks:
      - skynet

  front:
    build:
      context: ./static
      dockerfile: static/Dockerfile
    networks:
      - skynet

  nginx:
    image: nginx
    ports:
      - "8080:80"
    depends_on:
      - server
      - front
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    networks:
      - skynet

